package com.myspace.githook_1;

import lombok.Getter;
import lombok.Setter;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CountryResult implements CountryResultInterface {

	String notes;

	@Override
	public String getNotes() {
		return notes;
	}

	@Override
	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((notes == null) ? 0 : notes.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CountryResult other = (CountryResult) obj;
		if (notes == null) {
			if (other.notes != null)
				return false;
		} else if (!notes.equals(other.notes))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "CountryResult [notes=" + notes + "]";
	}
	
	
	

}