package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */


public class ShipmentObject implements  ShipmentObjectInterface {

	String countryCode;
	String countryName;
	String countryColor;
	String countryNumber;
	String countryNotes;
	
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
		
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getCountryColor() {
		return this.countryColor;
	}
	
	public void setCountryColor(String countryColor) {
		this.countryColor = countryColor;
	}
	
	public String getCountryNumber() {
		return this.countryNumber;
	}
	
	public void setCountryNumber(String countryNumber) {
		this.countryNumber = countryNumber;
	}

	public String getCountryNotes() {
		return this.countryNotes;
	}

	public void setCountryNotes(String countryNotes) {
		 this.countryNotes = countryNotes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((countryCode == null) ? 0 : countryCode.hashCode());
		result = prime * result + ((countryColor == null) ? 0 : countryColor.hashCode());
		result = prime * result + ((countryName == null) ? 0 : countryName.hashCode());
		result = prime * result + ((countryNotes == null) ? 0 : countryNotes.hashCode());
		result = prime * result + ((countryNumber == null) ? 0 : countryNumber.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ShipmentObject other = (ShipmentObject) obj;
		if (countryCode == null) {
			if (other.countryCode != null)
				return false;
		} else if (!countryCode.equals(other.countryCode))
			return false;
		if (countryColor == null) {
			if (other.countryColor != null)
				return false;
		} else if (!countryColor.equals(other.countryColor))
			return false;
		if (countryName == null) {
			if (other.countryName != null)
				return false;
		} else if (!countryName.equals(other.countryName))
			return false;
		if (countryNotes == null) {
			if (other.countryNotes != null)
				return false;
		} else if (!countryNotes.equals(other.countryNotes))
			return false;
		if (countryNumber == null) {
			if (other.countryNumber != null)
				return false;
		} else if (!countryNumber.equals(other.countryNumber))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ShipmentObject [countryCode=" + countryCode + ", countryName=" + countryName + ", countryColor="
				+ countryColor + ", countryNumber=" + countryNumber + ", countryNotes=" + countryNotes + "]";
	}
	
	
}